- app/src/index.js
- Replaced the hardcoded "abstract" with the searchKey value
Closes #16
> (#16) Hardcoded Abstract Key

- app/src/index.html
- app/src/index.scss
for #4 
First pass for abstract detail page done
- Fixed spacing on page
- Made sure font is Poppins
Started styling for search page
- Updated pagination style and sidenav style for the numbers
- Updated hex values
- Fixed spacing on page
- Fixed sidenav search button
> (#4) APP: Apply Styling to Widget

- app/src/index.scss
- Made left column for filters wider
- Made date published the size of a heading and section
> (#29) Widget QA Issues

- app/src/index.scss
- increased line height of specified areas
- removed indentation
- reduced space between specified areas
- added bullet points where needed
- decreased title font size
Closes #28
> (#28) Widget Design Changes

- .github/workflows/app-workflow.yml
> (#51) Update workflow ref

- rss/.gitignore
- rss/package-lock.json
- rss/package.json
- rss/src/__tests__/deleteFile.test.js
- rss/src/__tests__/generateStaticFiles.test.js
- rss/src/__tests__/netStorageUpload.test.js
- rss/src/__tests__/uploadToAkamai.test.js
- rss/src/__tests__/zipFolder.test.js
- rss/src/deleteFile.js
- rss/src/generateStaticFiles.js
- rss/src/main.js
- rss/src/netStorageUpload.js
- rss/src/uploadToAkamai.js
- rss/src/writeFile.js
- rss/src/zipFolder.js
> (#7) Enable the ability to upload to Akamai

- rss/src/__tests__/generateRSSFile.test.js
- rss/src/generateRSSFile.js
- rss/src/rss-files-config.js
- Updated link locations in rss-files-config.js
- XML file names are lowercase and use underscores
Closes #12
> (#12) Update Link Locations

- app/src/__tests__/ott.test.js
- app/src/index.scss
- changed button outline to match background
- changed hover color to be a darker blue instead of purple
Closes #54
> (#54) Update search button outline

- app/src/index.js
- app/src/index.scss
- changed font size to 18px (1.1250em)
- changed font family to Poppins
Closes #53
> (#53) Make search results Title more prominent

- app/src/index.js
> (#3) Add page loads to the EDDL

- app/src/index.js
> (#65) Add additional analytics details

- rss/src/rss-files-config.js
- changed field_govdelivery filter from false to true
Closes #9
> (#9) RSS: Limit to announce to GovDelivery only

- app/src/index.html
- app/src/index.js
> Update titles and breadcrumbs

- rss/src/__tests__/createRSSItem.test.js
- rss/src/__tests__/createRSSchannel.test.js
- rss/src/__tests__/generateRSSFile.test.js
- rss/src/__tests__/rssFilesConfig.test.js
- rss/src/createRSSItem.js
- rss/src/createRSSchannel.js
- rss/src/generateRSSFile.js
- rss/src/rss-files-config.js
- updated the link and guid to be correct links
Closes #74
> (#74) Update link locations to be correct

- rss/.gitignore
- rss/package-lock.json
- rss/package.json
- rss/src/__tests__/createRSSItem.test.js
- rss/src/__tests__/createRSSchannel.test.js
- rss/src/__tests__/createSitemap.test.js
- rss/src/__tests__/deleteFile.test.js
- rss/src/__tests__/generateRSSFile.test.js
- rss/src/__tests__/generateStaticFiles.test.js
- rss/src/__tests__/netStorageUpload.test.js
- rss/src/createRSSItem.js
- rss/src/createRSSchannel.js
- rss/src/createSitemap.js
- rss/src/generateRSSFile.js
- rss/src/main.js
- rss/src/netStorageUpload.js
- rss/src/uploadToAkamai.js
> (#79) Implement .env for environment variables

- app/src/index.js
- rss/src/rss-files-config.js
> (#82) Update returned results to include non-NCI abstracts

- app/src/index.scss
- removed width from css for pagination
- changed pagination item padding from a percentage to pixels
Closes #84
Closes #67
> (#84) Varying padding width in pagination numbers

- app/src/index.js
- rss/src/rss-files-config.js
> (#86) Filter only on data source

- app/.gitignore
- app/.npmignore
- app/package.json
> (#87) Add registry info to publish app

- rss/src/generateStaticFiles.js
> (#91) Use field_data_source for static files

- README.md
- rss/.gitignore
- rss/Dockerfile
- rss/run.sh
Adds the ability to run the RSS script within a docker container.
Closes #95
> (#95) Containerize RSS script
